# Generated by Django 5.2.14 on 2026-05-30 14:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0002_rename_name_product_title"),
    ]

    operations = [
        migrations.RenameField(
            model_name="product",
            old_name="image_url",
            new_name="image1_url",
        ),
        migrations.AddField(
            model_name="product",
            name="image2_url",
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="product",
            name="image3_url",
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="product",
            name="image4_url",
            field=models.URLField(blank=True, null=True),
        ),
    ]
